# Theme customization.
########################################################################################################################

fields:
    app_name:
        label: App Name
        type: text
        span: left
        default: CMS管理系統 教學網站
    app_href:
        label: App Href
        type: text
        default: ""
        span: right